-- H24 PR-6. equity_breadth_daily is a MATERIALIZED fold over nse_eod_bhavcopy, and every row in it
-- was computed with a `series = 'EQ'` population. PR-6 widens that fold to the EQ+BE cash universe,
-- so the stored rows are now wrong -- not stale-by-a-day, but computed over the wrong universe.
--
-- Truncating is what makes the series HOMOGENEOUS. Leaving the rows and letting the incremental job
-- correct forward would produce a chart with a silent discontinuity at the deploy date: EQ-only to
-- the left, EQ+BE to the right, no marker, and the jump would read as a market event rather than a
-- units change. Measured on live 2026-08-18: the widening moves a session's total from 2,624 to
-- 2,853 (+8.7%), which is exactly the size of step that looks like news.
--
-- EquityBreadthEodJob's boot pass refills it: with the table empty, latestDate() is null and the job
-- backfills `artha.breadth.backfill-days` of history in one SMA-warmed scan (compute() derives its
-- own warmup window, so the SMA-50/200 counts are correct from the first output day).
--
-- ⚠️ That config was 180 while the table already spanned 217 days, so this TRUNCATE would have
-- SILENTLY DROPPED ~37 days of history. The default is raised to 240 in the same PR
-- (EquityBreadthEodJob:54) -- there is no env override for it, so the @Value default is the
-- deployed value, verified against `docker inspect ay-market-data`. Do not deploy this migration
-- without that change.
--
-- Plain table, not a hypertable (checked), so TRUNCATE needs no Timescale-specific handling.
TRUNCATE TABLE equity_breadth_daily;
