package in.arthayantra.backtest.jobs;

import org.springframework.beans.factory.ObjectProvider;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.info.BuildProperties;
import org.springframework.boot.info.GitProperties;
import org.springframework.stereotype.Component;

/**
 * The engine CODE identity baked into this running jar — the git commit SHA + a build/image tag —
 * resolved ONCE at startup from the jar's {@code git.properties} / {@code build-info.properties}
 * (generated by the git-commit-id + spring-boot build-info plugins, H9 #617). Stamped onto every
 * {@code jobs} row (creating service) and {@code backtest_runs} row (executing worker) so two runs
 * of one strategy across a code deploy are distinguishable — research-fidelity audit P0-2 / R1.
 *
 * <p><b>Fail-soft.</b> The {@link GitProperties}/{@link BuildProperties} beans exist only when their
 * property files are on the classpath (Spring Boot's {@code ProjectInfoAutoConfiguration}). A mock /
 * test / source-tarball jar built without {@code .git} has neither bean, so both fields are simply
 * {@code null} — never an error, and the additive-nullable columns stay NULL for such rows.
 */
@Component
public class EngineIdentity {

  private final String sha;
  private final String image;

  private EngineIdentity(String sha, String image) {
    this.sha = sha;
    this.image = image;
  }

  /** Production wiring: reads the auto-configured beans if present, else leaves both fields null. */
  @Autowired
  public EngineIdentity(ObjectProvider<GitProperties> git, ObjectProvider<BuildProperties> build) {
    this(shaOf(git.getIfAvailable()), imageOf(build.getIfAvailable()));
  }

  /** Test/explicit factory — pins the two values directly (no Spring context). */
  public static EngineIdentity of(String sha, String image) {
    return new EngineIdentity(sha, image);
  }

  /** The full git commit SHA of this jar, or {@code null} when {@code git.properties} is absent. */
  public String sha() {
    return sha;
  }

  /** The build image tag ({@code <artifact>:<version>}), or {@code null} when build-info is absent. */
  public String image() {
    return image;
  }

  private static String shaOf(GitProperties git) {
    // Full commit id — matches the `git.commit.id` that `ay verify-deploy` reads from /actuator/info.
    return git == null ? null : git.getCommitId();
  }

  private static String imageOf(BuildProperties build) {
    if (build == null) {
      return null;
    }
    // The runtime docker tag is always the mutable ":dev"; the jar's own build-info artifact:version
    // is the honest self-reportable build identity (paired with the SHA for deploy-distinction).
    String artifact = build.getArtifact() == null ? build.getName() : build.getArtifact();
    return artifact + ":" + build.getVersion();
  }
}
